MobileOperator/MainApp/src/main/java/model/dto/AbstractDto.java
package model.dto;

public abstract class AbstractDto {

    public boolean isNew() {
        return (this.getId() == null);
    }

    private Integer id;
    private Boolean valid;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Boolean getValid() {
        return valid;
    }

    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}

MobileOperator/MainApp/src/main/java/model/dto/AccountDto.java
package model.dto;

import java.util.Objects;

public class AccountDto extends AbstractDto {
    private String login;
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AccountDto that = (AccountDto) o;
        return Objects.equals(login, that.login) &&
                Objects.equals(password, that.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(login, password);
    }
}

MobileOperator/MainApp/src/main/java/model/dto/AdditionDto.java
package model.dto;

import com.fasterxml.jackson.annotation.JsonBackReference;
import model.entities.Addition;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.*;

/**
 * DTO for Option
 * It contains: option's name, its price and a cost of option's service activation
 */
public class AdditionDto extends AbstractDto implements Serializable {
    private String name;
    private Addition.Parameter parameter;
    private int value;
    private BigDecimal price;
    private BigDecimal additionActivationCost;
    @JsonBackReference
    private List<PackageDto> packages = new ArrayList<>();
    private Set<AdditionDto> mandatoryAdditions = new HashSet<>();
    private Set<AdditionDto> incompatibleAdditions = new HashSet<>();

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getAdditionActivationCost() {
        return additionActivationCost;
    }

    public void setAdditionActivationCost(BigDecimal additionActivationCost) {
        this.additionActivationCost = additionActivationCost;
    }

    public Addition.Parameter getParameter() {
        return parameter;
    }

    public void setParameter(Addition.Parameter parameter) {
        this.parameter = parameter;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public List<PackageDto> getPackages() {
        return packages;
    }

    public void setPackages(List<PackageDto> packages) {
        this.packages = packages;
    }

    public Set<AdditionDto> getMandatoryAdditions() {
        return mandatoryAdditions;
    }

    public void setMandatoryAdditions(Set<AdditionDto> mandatoryAdditions) {
        this.mandatoryAdditions = mandatoryAdditions;
    }

    public Set<AdditionDto> getIncompatibleAdditions() {
        return incompatibleAdditions;
    }

    public void setIncompatibleAdditions(Set<AdditionDto> incompatibleAdditions) {
        this.incompatibleAdditions = incompatibleAdditions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AdditionDto that = (AdditionDto) o;
        return value == that.value &&
                Objects.equals(name, that.name) &&
                parameter == that.parameter &&
                Objects.equals(price, that.price) &&
                Objects.equals(additionActivationCost, that.additionActivationCost);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, parameter, value, price, additionActivationCost);
    }


}

MobileOperator/MainApp/src/main/java/model/dto/AdditionFormDto.java
package model.dto;

import model.entities.Addition;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Set;

public class AdditionFormDto extends AbstractDto {
    private String name;
    private Addition.Parameter parameter;
    private int value;
    private BigDecimal price;
    private BigDecimal additionActivationCost;
    private List<Integer> tariffIds;
    private List<Integer> mandatoryIds;
    private List<Integer> incompatibleIds;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getAdditionActivationCost() {
        return additionActivationCost;
    }

    public void setAdditionActivationCost(BigDecimal additionActivationCost) {
        this.additionActivationCost = additionActivationCost;
    }

    public Addition.Parameter getParameter() {
        return parameter;
    }

    public void setParameter(Addition.Parameter parameter) {
        this.parameter = parameter;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public List<Integer> getTariffIds() {
        return tariffIds == null ? new ArrayList<>() : tariffIds;
    }

    public void setTariffIds(List<Integer> tariffIds) {
        this.tariffIds = tariffIds;
    }

    public List<Integer> getMandatoryIds() {
        return mandatoryIds;
    }

    public void setMandatoryIds(List<Integer> mandatoryIds) {
        this.mandatoryIds = mandatoryIds;
    }

    public List<Integer> getIncompatibleIds() {
        return incompatibleIds;
    }

    public void setIncompatibleIds(List<Integer> incompatibleIds) {
        this.incompatibleIds = incompatibleIds;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AdditionFormDto that = (AdditionFormDto) o;
        return value == that.value &&
                Objects.equals(name, that.name) &&
                parameter == that.parameter &&
                Objects.equals(price, that.price) &&
                Objects.equals(additionActivationCost, that.additionActivationCost) &&
                Objects.equals(tariffIds, that.tariffIds) &&
                Objects.equals(mandatoryIds, that.mandatoryIds) &&
                Objects.equals(incompatibleIds, that.incompatibleIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, parameter, value, price, additionActivationCost, tariffIds, mandatoryIds, incompatibleIds);
    }
}

MobileOperator/MainApp/src/main/java/model/dto/AdditionRelationDto.java
package model.dto;

import model.entities.AdditionRelation.Relation;

import java.io.Serializable;
import java.util.Objects;

public class AdditionRelationDto implements Serializable {
    private AdditionDto mainAddition;
    private AdditionDto relativeAddition;
    private Relation relation;

    public AdditionDto getMainAddition() {
        return mainAddition;
    }

    public void setMainAddition(AdditionDto mainAddition) {
        this.mainAddition = mainAddition;
    }

    public AdditionDto getRelativeAddition() {
        return relativeAddition;
    }

    public void setRelativeAddition(AdditionDto relativeAddition) {
        this.relativeAddition = relativeAddition;
    }

    public Relation getRelation() {
        return relation;
    }

    public void setRelation(Relation relation) {
        this.relation = relation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AdditionRelationDto that = (AdditionRelationDto) o;
        return Objects.equals(mainAddition, that.mainAddition) &&
                Objects.equals(relativeAddition, that.relativeAddition) &&
                relation == that.relation;
    }

    @Override
    public int hashCode() {
        return Objects.hash(mainAddition, relativeAddition, relation);
    }
}

MobileOperator/MainApp/src/main/java/model/dto/AdminDto.java
package model.dto;

public class AdminDto extends AbstractDto {
    private String login;
    private String password;

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

MobileOperator/MainApp/src/main/java/model/dto/Basket.java
package model.dto;

import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

@Component
public class Basket implements Serializable {
    private TariffDto chosenTariff;
    private Set<AdditionDto> chosenAdditions = new HashSet<>();
    private Set<AdditionDto> deletedAdditions = new HashSet<>();
    private BigDecimal totalPrice;
    private BigDecimal totalActivationCost;
    private BigDecimal totalSum;

    public void totalSum() {
        totalSum = totalPrice.add(totalActivationCost);
    }

    public boolean isFree() {
        return chosenTariff == null && chosenAdditions.isEmpty();
    }

    public void clear() {
        this.totalActivationCost = BigDecimal.ZERO;
        this.totalPrice = BigDecimal.ZERO;
        this.totalSum = BigDecimal.ZERO;
        this.chosenAdditions.clear();
        this.deletedAdditions.clear();
        this.chosenTariff = null;
    }

    public void chooseTariff(TariffDto tariff) {
        TariffDto previousTariff = chosenTariff;
        setChosenTariff(tariff);
        chosenTariff = tariff;
        if (previousTariff != null) {
            totalPrice = totalPrice.subtract(previousTariff.getPrice())
                    .add(chosenTariff.getPrice());
        } else {
            totalPrice = totalPrice.add(chosenTariff.getPrice());
        }
        totalSum();
    }

    public void removeTariff() {
        TariffDto previousTariff = chosenTariff;
        setChosenTariff(null);
        totalPrice = totalPrice.subtract(previousTariff.getPrice());
        totalSum();
    }

    public void addAddition(Set<AdditionDto> additionList) {
        for (AdditionDto addition : additionList) {
            if (!chosenAdditions.contains(addition)) {
                chosenAdditions.add(addition);
                totalPrice = totalPrice.add(addition.getPrice());
                totalActivationCost = totalActivationCost.add(
                        addition.getAdditionActivationCost());
                totalSum();
            }
        }
    }

    public void removeAllAdditions(Set<AdditionDto> additionList) {
        for (AdditionDto addition : additionList) {
            removeAddition(addition);
        }
    }

    public void removeBasketAdd(AdditionDto additionDto) {
        removeAddition(additionDto);
        if (deletedAdditions.contains(additionDto)) {
            deletedAdditions.remove(additionDto);
        }
    }

    public void removeAddition(AdditionDto additionDto) {
        if (chosenAdditions.contains(additionDto)) {
            chosenAdditions.remove(additionDto);
            totalPrice = totalPrice.subtract(additionDto.getPrice());
            totalActivationCost = totalActivationCost.subtract(
                    additionDto.getAdditionActivationCost());
            totalSum();
        }
    }

    public TariffDto getChosenTariff() {
        return chosenTariff;
    }

    public void setChosenTariff(TariffDto chosenTariff) {
        this.chosenTariff = chosenTariff;
    }

    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    public BigDecimal getTotalActivationCost() {
        return totalActivationCost;
    }

    public void setTotalActivationCost(BigDecimal totalActivationCost) {
        this.totalActivationCost = totalActivationCost;
    }

    public BigDecimal getTotalSum() {
        return totalSum;
    }

    public void setTotalSum(BigDecimal totalSum) {
        this.totalSum = totalSum;
    }

    public Set<AdditionDto> getChosenAdditions() {
        return chosenAdditions;
    }

    public void setChosenAdditions(Set<AdditionDto> chosenAdditions) {
        this.chosenAdditions = chosenAdditions;
    }

    public Set<AdditionDto> getDeletedAdditions() {
        return deletedAdditions;
    }

    public void setDeletedAdditions(Set<AdditionDto> deletedAdditions) {
        this.deletedAdditions = deletedAdditions;
    }
}

MobileOperator/MainApp/src/main/java/model/dto/ClientDto.java
package model.dto;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DTO for Client.
 * It contains: client's name and surname, client's birthday, passport data,
 * the address, number of contract, email and password for client's personal account.
 */

public class ClientDto extends AbstractDto {
    private String name;
    private String surname;
    private String birthday;
    private String passportSeries;
    private String passportNumber;
    private String passportIssuedBy;
    private String passportIssueDate;
    private String passportDivisionCode;
    private String address;
    private String email;
    @JsonManagedReference
    private List<ContractDto> contracts = new ArrayList<>();

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getPassportSeries() {
        return passportSeries;
    }

    public void setPassportSeries(String passportSeries) {
        this.passportSeries = passportSeries;
    }

    public String getPassportNumber() {
        return passportNumber;
    }

    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
    }

    public String getPassportIssuedBy() {
        return passportIssuedBy;
    }

    public void setPassportIssuedBy(String passportIssuedBy) {
        this.passportIssuedBy = passportIssuedBy;
    }

    public String getPassportIssueDate() {
        return passportIssueDate;
    }

    public void setPassportIssueDate(String passportIssueDate) {
        this.passportIssueDate = passportIssueDate;
    }

    public String getPassportDivisionCode() {
        return passportDivisionCode;
    }

    public void setPassportDivisionCode(String passportDivisionCode) {
        this.passportDivisionCode = passportDivisionCode;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public List<ContractDto> getContracts() {
        return contracts;
    }

    public void setContracts(List<ContractDto> contracts) {
        this.contracts = contracts;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClientDto clientDto = (ClientDto) o;
        return Objects.equals(name, clientDto.name) &&
                Objects.equals(surname, clientDto.surname) &&
                Objects.equals(birthday, clientDto.birthday) &&
                Objects.equals(passportSeries, clientDto.passportSeries) &&
                Objects.equals(passportNumber, clientDto.passportNumber) &&
                Objects.equals(passportIssuedBy, clientDto.passportIssuedBy) &&
                Objects.equals(passportIssueDate, clientDto.passportIssueDate) &&
                Objects.equals(passportDivisionCode, clientDto.passportDivisionCode) &&
                Objects.equals(address, clientDto.address) &&
                Objects.equals(email, clientDto.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, surname, birthday, passportSeries, passportNumber,
                passportIssuedBy, passportIssueDate, passportDivisionCode, address, email);
    }

    @Override
    public String toString() {
        return "ClientDto{" +
                "name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", birthday='" + birthday + '\'' +
                ", passportSeries='" + passportSeries + '\'' +
                ", passportNumber='" + passportNumber + '\'' +
                ", passportIssuedBy='" + passportIssuedBy + '\'' +
                ", passportIssueDate='" + passportIssueDate + '\'' +
                ", passportDivisionCode='" + passportDivisionCode + '\'' +
                ", address='" + address + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}

MobileOperator/MainApp/src/main/webapp/accountList.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: gleb
  Date: 17.09.18
  Time: 11:11
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Accounts</title>
</head>
<body>
<c:set value="${pageContext.request.contextPath}" var="contextPath"/>
<form:form method="get" action="${contextPath}/returnToAdminPage">
    <table>
        <tr>
            <th>Id</th>
            <th>Login</th>
            <th>Password</th>
        </tr>
        <c:forEach items="${accounts}" var="acc">
            <tr>
                <td>${acc.id}</td>
                <td>${acc.login}</td>
                <td>${acc.password}</td>
            </tr>
        </c:forEach>
    </table>
    <input type="submit" value="Return">
</form:form>
</body>
</html>

MobileOperator/MainApp/src/main/webapp/additionForm.jsp
<%@ page session="false" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <jsp:include page="header.jsp"/>
    <title>Addition</title>
</head>
<body>
<c:set value="${pageContext.request.contextPath}" var="contextPath"/>
<div class="container">

    <c:choose>
        <c:when test="${addition['new']}">
            <h1>Add addition</h1>
        </c:when>
        <c:otherwise>
            <h1>Update addition</h1>
        </c:otherwise>
    </c:choose>
    <br/>

    <spring:url value="/employee/additions" var="additionActionUrl"/>

    <form:form class="form-horizontal" method="post" modelAttribute="addition" action="${additionActionUrl}">

        <form:hidden path="id"/>

        <spring:bind path="name">
            <div class="form-group ${status.error ? 'has-error' : ''}">
                <label class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                    <form:input path="name" type="text" class="form-control " id="name" placeholder="Name"/>
                    <form:errors path="name" class="control-label"/>
                </div>
            </div>
        </spring:bind>

        <spring:bind path="parameter">
            <div class="form-group ${status.error ? 'has-error' : ''}">
                <label class="col-sm-2 control-label">Parameter</label>
                <div class="col-sm-10">
                    <form:select path="parameter">
                        <c:forEach items="${parameterEnum}" var="parameter">
                            <form:option value="${parameter}"/>
                        </c:forEach>
                    </form:select>
                </div>
            </div>
        </spring:bind>

        <spring:bind path="value">
            <div class="form-group ${status.error ? 'has-error' : ''}">
                <label class="col-sm-2 control-label">Value</label>
                <div class="col-sm-10">
                    <form:input path="value" type="text" class="form-control" id="value" placeholder="value"/>
                    <form:errors path="value" class="control-label"/>
                </div>
            </div>
        </spring:bind>

        <spring:bind path="price">
            <div class="form-group ${status.error ? 'has-error' : ''}">
                <label class="col-sm-2 control-label">Price</label>
                <div class="col-sm-10">
                    <form:input path="price" type="text" class="form-control" id="price" placeholder="price"/>
                    <form:errors path="price" class="control-label"/>
                </div>
            </div>
        </spring:bind>

        <spring:bind path="additionActivationCost">
            <div class="form-group ${status.error ? 'has-error' : ''}">
                <label class="col-sm-2 control-label">Activation cost</label>
                <div class="col-sm-10">
                    <form:input path="additionActivationCost" type="text" class="form-control"
                                id="additionActivationCost" placeholder="Actisvation cost"/>
                    <form:errors path="additionActivationCost" class="control-label"/>
                </div>
            </div>
        </spring:bind>
        <spring:bind path="tariffIds">
            <div class="form-group">
                <label class="col-sm-2 control-label">Incompatible tariffs</label>
                <div class="col-sm-10">
                    <form:select path="tariffIds" multiple="true" size="">
                        <c:forEach varStatus="loop" items="${tariffList}" var="tariff">
                            <form:option value="${tariff.id}">${tariff.name} (${tariff.description})</form:option>
                        </c:forEach>
                    </form:select>
                </div>
            </div>
        </spring:bind>
        <div class="form-group">
            <label class="col-sm-2 control-label">Mandatory options</label>
            <div class="col-sm-10">
                <form:select path="mandatoryIds" multiple="true" size="">
                    <c:forEach varStatus="loop" items="${additionList}" var="add">
                        <form:option value="${add.id}">${add.name}</form:option>
                    </c:forEach>
                </form:select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Incompatible options</label>
            <div class="col-sm-10">
                <form:select path="incompatibleIds" multiple="true" size="">
                    <c:forEach varStatus="loop" items="${additionList}" var="add">
                        <form:option value="${add.id}">${add.name}</form:option>
                    </c:forEach>
                </form:select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <c:choose>
                    <c:when test="${addition['new']}">
                        <button type="submit" class="btn-lg btn-primary pull-right">Add</button>
                    </c:when>
                    <c:otherwise>
                        <button type="submit" class="btn-lg btn-primary pull-right">Update</button>
                    </c:otherwise>
                </c:choose>
            </div>
        </div>
    </form:form>
</div>
<jsp:include page="footer.jsp"/>
</body>
</html>

MobileOperator/MainApp/src/main/webapp/clientEnterPsw.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Enter password</title>
</head>
<body>
<c:set value="${pageContext.request.contextPath}" var="contextPath"/>
    <form:form modelAttribute="contract" action="${contextPath}/${contract.id}/confirmPsw" method="post">
        Enter your password: <form:password path="password"/>
        <input type="submit" value="Log in"/>
    </form:form>

    <form action="${contextPath}/clientLogInForm" method="get">
        <input type="submit" value="Return"/>
    </form>
</body>
</html>

MobileOperator/MainApp/src/main/webapp/error.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: gleb
  Date: 07.09.18
  Time: 11:41
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html; charset=UTF-8" %>
<html>
<head>
</head>
<body>
<c:set value="${pageContext.request.contextPath}" var="contextPath"/>
<h3>Please enter the correct details</h3>
<table>
    <tr>
        <td><a href="${contextPath}/showClients">Retry</a></td>
    </tr>
</table>
</body>

</html>

MobileOperator/MainApp/src/main/webapp/personalTariffList.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta charset="utf-8">
    <%--<meta name="viewport" content="width=device-width, initial-scale=1">--%>
    <title>Tariffs</title>
    <jsp:include page="header.jsp"/>
</head>
<body style="margin-left: 100px; margin-top: 20px">
<c:set value="${pageContext.request.contextPath}" var="contextPath"/>
<form:form method="get" action="${contextPath}/client/returnToClientPage">
    <button type="submit" class="btn btn-primary btn-lg">Return</button>
</form:form>
<div style="float: left; margin-right: 100px">
    <h1>All Tariffs</h1>
    <table class="table table-striped" style="font-size: x-large">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>SMS</th>
            <th>Minutes</th>
            <th>Internet</th>
            <th>Price</th>
        </tr>
        </thead>

        <c:forEach var="tariff" items="${tariffList}">
            <tr>
                <td>${tariff.id}</td>
                <td>${tariff.name}</td>
                <td>${tariff.sms}</td>
                <td>${tariff.minutes}</td>
                <td>${tariff.internet} Gb</td>
                <td>${tariff.price} &#8381</td>
                <td>
                    <c:choose>
                        <c:when test="${tariff.id eq contract.tariff.id}">
                            <c:out value="This tariff is yours"/>
                        </c:when>
                        <c:otherwise>
                            <form action="${contextPath}/client/${tariff.id}/chooseTariff" method="post">
                                <input type="submit" value="Add to basket"/>
                            </form>
                        </c:otherwise>
                    </c:choose>
                </td>
            </tr>
        </c:forEach>
    </table>
</div>

<div style="float: left; font-size: x-large">
    <div class="text-lg-center">
        <h1>Current balance: ${contract.balance} &#8381</h1>
    </div>
    <div>
        <h1 class="text-center" id="btnBasket">Basket</h1>
    </div>
    <div id="divBasket" style="display: none">
        <table class="table table-bordered table-striped text-center" style="font-size: x-large">
            <c:if test="${not basket.free}">
                <tr class="thead-dark">
                    <th style="background: #FFFFFF; border: 0"></th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Act-cost</th>
                </tr>
                <c:if test="${basket.chosenTariff != null}">
                    <tr>
                        <td>
                            <form action="${contextPath}/client/removeBasketTariffFromOptions" method="post">
                                <input type="submit" value="X">
                            </form>
                        </td>
                        <td>
                            <p><b>Tariff: </b>${basket.chosenTariff.name}</p>
                        </td>
                        <td>${basket.chosenTariff.price}</td>
                        <td>0</td>
                    </tr>
                </c:if>

                <c:if test="${not empty basket.chosenAdditions}">
                    <c:forEach varStatus="loop" items="${basket.chosenAdditions}" var="addition">
                        <tr>
                            <td>
                                <form action="${contextPath}/client/${addition.id}/removeBasketAddFromOptions"
                                      method="post">
                                    <input type="submit" value="X">
                                </form>
                            </td>
                            <td>${addition.name}</td>
                            <td>${addition.price}</td>
                            <td>${addition.additionActivationCost}</td>
                        </tr>
                    </c:forEach>
                </c:if>
            </c:if>
        </table>

        <c:if test="${not empty basket.deletedAdditions}">
            <b>Remove options:</b><br/>
            <c:forEach varStatus="loop" items="${basket.deletedAdditions}" var="addition">
                <form action="${contextPath}/client/${addition.id}/removeBasketAddFromOptions" method="post">
                    <input type="submit" value="X"><c:out value="${addition.name}"/>
                </form>
            </c:forEach>
        </c:if>

        <br/><br/><b>Price:</b>
        <c:out value="${basket.totalPrice}" default="0.0"/> &#8381 <br/>
        <b>Total activation cost:</b>
        <c:out value="${basket.totalActivationCost}" default="0.0"/> &#8381 <br/><br/>
        <b>TOTAL:</b>
        <c:out value="${basket.totalSum}" default="0.0"/> &#8381 <br/>

        <form action="${contextPath}/client/submitBasket" method="post">
            <c:choose>
                <c:when test="${basket.free and empty basket.deletedAdditions}">
                    <input type="submit" value="Buy it!" disabled/>
                </c:when>
                <c:otherwise>
                    <c:if test="${contract.balance < basket.totalSum}">
                        <p style="color: #b21f2d">Please top up your balance!</p>
                        <input type="submit" value="Buy it!" disabled/>
                    </c:if>
                    <c:if test="${contract.balance >= basket.totalSum}">
                        <input type="submit" value="Buy it!"/>
                    </c:if>
                </c:otherwise>
            </c:choose>
        </form>
    </div>
</div>
<jsp:include page="footer.jsp"/>
<script>
    $(function () {
        $("#btnBasket").click(function () {
            $("#divBasket").slideToggle("fast");
        })
    })
</script>
</body>
</html>